yarnPath: .yarn/releases/yarn-3.3.0.cjs
packageExtensions:
  "@storybook/react@*":
    dependencies:
      "react-dom": "*"
      "react": "*"
  "@storybook/cli@*":
    dependencies:
      "react-dom": "*"
      "react": "*"
  "@storybook/core-common@*":
    dependencies:
      "@storybook/react-vite": "^7.0.0-beta.8"
